files:
  - source: /frappe/locale/main.pot
    translation: /frappe/locale/%locale_with_underscore%.po
pull_request_title: "fix: sync translations from crowdin"
pull_request_labels:
  - translation
commit_message: "fix: %language% translations"
append_commit_message: false
